services:
  app-hub:
    container_name: app-hub
    build: .
    ports:
      - 5173:5173
    volumes:
      - app-hub-data:/app/data
    restart: unless-stopped
    networks:
      - umbrel

volumes:
  app-hub-data:

networks:
  umbrel:
    driver: bridge
