version: '3.8'

services:
  frontend:
    build: .
    container_name: app-hub
    ports:
      - "5173:5173"
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: npm run dev
